### ISSUE TITLE
Icons at bottom do not appear to be displaying properly.

### ISSUE THREAD

**Issue by jongrover** [kiddkat/new_portfolio#3]
![screen shot 2014-08-22 at 1 05 47 pm](https://cloud.githubusercontent.com/assets/1154377/4014253/a0b01b88-2a1e-11e4-8797-5756d35b5e67.png)

**Comment by kiddkat** [comment]
I know. I fixed it originally by loading the font awesome text, which apparently, made dupes, that was later fixed. Now I'm not sure how to fix them. But I'll give it the old college try. :)
